<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>Dashboard_home</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>test</label>
    <navType>Console</navType>
    <setupExperience>service</setupExperience>
    <tabs>standard-Account</tabs>
    <tabs>AppLog__c</tabs>
    <tabs>MarketingFlyer__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>test_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>AppLog__c</tab>
        </mappings>
        <mappings>
            <tab>MarketingFlyer__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
