<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>test</label>
    <navType>Console</navType>
    <setupExperience>service</setupExperience>
    <tabs>standard-Account</tabs>
    <tabs>AppLog__c</tabs>
    <tabs>testForDeletion__c</tabs>
    <tabs>Parent_Object__c</tabs>
    <tabs>Child_Object__c</tabs>
    <tabs>Template__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>test_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>AppLog__c</tab>
        </mappings>
        <mappings>
            <tab>Child_Object__c</tab>
        </mappings>
        <mappings>
            <tab>Parent_Object__c</tab>
        </mappings>
        <mappings>
            <tab>Template__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>testForDeletion__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
